### ISSUE TITLE
bgio-firebase not found

### ISSUE THREAD

**Issue by nahuelhds** [delucis/bgio-firebase#1]
Hi! I've just tried to install the package but it says it doesn't exists.

![image](https://user-images.githubusercontent.com/1885647/78742247-e0cb4e00-7931-11ea-9333-be85cc85479d.png)

Any lead?

**Comment by delucis** [comment]
Hey! Yes, I’ve just been putting together the finishing touches to make the connector fully compatible with the latest boardgame.io. Should be releasing tomorrow. I’ll post here once it’s published.

**Comment by delucis** [comment]
@nahuelhds Just published the initial release. Let me know if you have any issues!

**Comment by nahuelhds** [comment]
Nice! Thanks! I'll give it a try in the next few days.
